<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.10.4" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.6.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VladyslavOrlovPromo.Core\VladyslavOrlovPromo.Core.csproj" />
    <ProjectReference Include="..\VladyslavOrlovPromo.Repositories\VladyslavOrlovPromo.Repositories.csproj" />
    <ProjectReference Include="..\VladyslavOrlovPromo.Services\VladyslavOrlovPromo.Services.csproj" />
  </ItemGroup>



</Project>
