<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VladyslavOrlovPromo.Core\VladyslavOrlovPromo.Core.csproj" />
    <ProjectReference Include="..\VladyslavOrlovPromo.Repositories\VladyslavOrlovPromo.Repositories.csproj" />
    <ProjectReference Include="..\VladyslavOrlovPromo.Services\VladyslavOrlovPromo.Services.csproj" />
  </ItemGroup>



</Project>
